config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :users, only: [:index, :show] do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :posts, only: [:index, :show, :create, :destroy] do
    resources :photos, only: [:create]
    resources :likes, only: [:create, :destroy], shallow: true
    resources :comments, only: [:index, :create, :destroy], shallow: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post

  validates :image, presence: true

  mount_uploader :image, PhotoUploader
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  scope :recent_post, -> {order created_at: :desc}

  def is_belongs_to? user
    Post.find_by(user_id: user.id, id: id)
  end

  def is_liked? user
    liked_by_user(user).present?
  end

  def liked_by_user user
    likes.select { |like| like.user_id == user.id }
  end

  def likes_sort_by_created_at
    likes.sort { |a, b| b.created_at <=> a.created_at }
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :name, presence: true, length: {maximum: 50}

  has_many :posts, dependent: :destroy
  has_many :likes
  has_many :comments
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def self.get_user_not_yet_follow
    all
  end

  def post_of_following
    following_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
    Post.where("user_id IN (#{following_ids}) OR user_id = :user_id", user_id: id)
  end

  def users_yet_follow
    following_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
    User.where("id NOT IN (#{following_ids})", user_id: id)
  end

  def self.search(term)
    if term
      where('name LIKE ?', "%#{term}%")
    else
      nil
    end
  end

  def update_without_current_password(params, *options)
    params.delete(:current_password)
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end
    result = update(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :website, :bio])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @comments = @post.comments.includes :user
  end

  def create
    @comment = current_user.comments.build comment_params
    @comment.post_id = params[:post_id]
    if @comment.save
      @post = @comment.post
    else
      flash[:alert] = "Something went wrong ..."
    end
    respond_to :js
  end

  def destroy
    @comment = Comment.find params[:id]
    @post = @comment.post
    if @comment.destroy
    else
      flash[:alert] = "Something went wrong ..."
    end
    respond_to :js
  end

  private
  
  def comment_params
    params.required(:comment).permit :content
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    if @like.save
      respond_to do |format|
        format.js {render layout: false}
      end
    else
      flash[:alert] = "Something went wrong ..."
    end
  end

  def destroy
    @like = Like.find(params[:id])
    @post = @like.post
    if @like.destroy
      respond_to :js
    else
      flash[:alert] = "Something went wrong ..."
    end
  end

  private
  def like_params
    params.permit :post_id
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if !user_signed_in?
      redirect_to new_user_session_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post, only: [:show, :destroy]

  def index
    @posts = Post.eager_load(:photos, :user, likes: :user, comments: :user).order(created_at: :desc).page(params[:page]).per(5)
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if params[:images].nil?
      flash[:alert] = "Posts must have pictures"
      redirect_to posts_path
      return
    end
    if @post.save
      if params[:images]
        params[:images].each do |img|
          @post.photos.create(image: img)
        end
      end

      redirect_to posts_path
      flash[:notice] = "Saved ..."
    else
      flash[:alert] = "Something went wrong ..."
      redirect_to posts_path
    end
  end

  def show
    @photos = @post.photos
    @likes = @post.likes.includes :user
    @comment = Comment.new
    @is_likes = @post.is_liked? current_user
  end

  def destroy
    if @post.user == current_user
      if @post.destroy
        flash[:notice] = "Post deleted!"
      else
        flash[:alert] = "Something went wrong ..."
      end
    else
      flash[:notice] = "You don't have permission to do that!"
    end
    redirect_to root_path
  end

  private

  def find_post
    @post = Post.find_by id: params[:id]

    return if @post
    flash[:danger] = "Post not exist!"
    redirect_to root_path
  end

  def post_params
    params.require(:post).permit :content
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  def after_update_path_for(resource)
    user_path(resource)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find_by id: params[:followed_id]
    current_user.follow @user
    @find_relationship = current_user.active_relationships
                                      .find_by followed_id: @user.id
    respond_to do |format|
      format.html{redirect_to @user}
      format.js
    end
  end

  def destroy
    @user = Relationship.find_by(id: params[:id]).followed
    current_user.unfollow @user
    @build_relationship = current_user.active_relationships.build
    respond_to do |format|
      format.html{redirect_to @user}
      format.js
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:search].nil?
      @users = User.all
    else
      @users = User.search(params[:search])
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.includes(:photos, :likes, :comments)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url (user)
    if user.image.nil?
      user.image = "user.jpeg"
    else
      user.image = user.image
    end
  end
end

app/views/comments/create.js.erb
$('#comment-post-<%= @post.id.to_s %>').html('<%= j render "posts/comment_list", {comments: @post.comments} %>');
$('#comment-form-post-<%= @post.id.to_s %> #comment_content').val('');

app/views/comments/destroy.js.erb
$('#comment-post-<%= @post.id.to_s %>').html('<%= j render "posts/comment_list", {comments: @post.comments} %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MetaGram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' if current_user %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>

    <% if flash.any? %>
      <script type="text/javascript">
        <% flash.each do |key, value| %>
          <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
          toastr.<%= type %>('<%= value %>')
        <% end %>
      </script>
    <% end %>
  </body>
</html>

app/views/likes/create.js.erb
$('#like-icon-post-<%= @post.id.to_s %>').html('<%= link_to like_path(@post.liked_by_user(current_user)), method: :delete, remote: true, class:"core-sprite loved hide-text" do %><i class="fas fa-heart fa-lg" style="color:red"></i><% end %>');
$('#like-text-post-<%= @post.id.to_s %>').html('<%= j render "posts/like_text", {likes: @post.likes_sort_by_created_at} if @post.likes.present? %>');

app/views/likes/destroy.js.erb
$('#like-icon-post-<%= @post.id %>').html('<%= link_to post_likes_path(@post), method: :post, remote: true, class:"core-sprite love hide-text" do %><i class="far fa-heart fa-lg"></i><% end %>');
$('#like-text-post-<%= @post.id %>').html('<%= j render "posts/like_text", {likes: @post.likes_sort_by_created_at} if @post.likes.present? %>');

app/views/pages/home.html.erb
<%= link_to "Log out", destroy_user_session_path, method: :delete %>
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/posts/_comment_form.html.erb
<%= form_for [post, Comment.new], :html => {:class => "w-100"}, remote: true do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :post_id, value: post.id %>
  <%= f.text_field :content, class: "form-control comment-input border-0", placeholder: "Add a comment ...", autocomplete: :off %>
<% end %>

app/views/posts/_comment_list.html.erb
<% comments.each do |comment| %>
  <div class="my-2">
    <% if comment.user == current_user %>
      <%= link_to "Delete comment", comment_path(comment), method: :delete, remote: true, class: "core-sprite delete-comment hide-text" %>
    <% end %>
    <span>
      <strong>
        <%= link_to comment.user.name, user_path(comment.user), class: "no-text-decoration normal-color" %>
      </strong>
    </span>
    <span><%= comment.content %></span>
  </div>
<% end %>

app/views/posts/_like_icon.html.erb
<% if is_liked.present? %>
  <%= link_to "Love", like_path(is_liked), method: :delete, remote: true,
    class: "core-sprite loved hide-text" %>
<% else %>
  <%= link_to "Loved", post_likes_path(post), method: :post, remote: true,
    class: "core-sprite love hide-text" %>
<% end %>

app/views/posts/_like_text.html.erb
<% if likes.length == 1 %>
  <strong><%= likes[0].user.name %></strong>
<% elsif likes.length == 2 %>
  <strong><%= likes[0].user.name + " and " + likes[1].user.name %></strong>
<% else %>
  <strong><%= "#{likes[0].user.name}, #{likes[1].user.name}" %></strong>
  <%= "and #{(likes.length - 2)} orther#{(likes.length - 2) > 1 ? "s" : nil}" %>
<% end %> liked this

app/views/posts/_photos.html.erb
<%= link_to post_path(post) do %>
  <% if post.photos.present? %>
    <% if post.photos.size == 1 %>
      <% if post.photos.first.image.present? %>
        <%= image_tag post.photos.first.image.url(:standard), :cloud_name => "cloudinary", class: "card-img-top" %>
      <% end %>
    <% else %>
      <div class="carousel slide" data-ride="carousel" id="carousel-post-<%= post.id %>">
        <div class="carousel-inner">
          <% post.photos.each do |photo| %>
            <div class="carousel-item<%= " active" if photo == post.photos.first %>">
              <% if photo.image.present? %>
                <%= image_tag photo.image.url(:standard), class: "card-img-top" %>
              <% end %>
            </div>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carousel-post-<%= post.id %>" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carousel-post-<%= post.id %>" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/posts/_posts_list.html.erb
<% @posts.each do |post| %>
  <div class="card mt-3 post">
    <div class="card-header d-flex align-items-center">
      <%= link_to user_path(post.user), class: "no-text-decoration" do %>
        <%= image_tag avatar_url(post.user), class: "post-author-icon" %>
      <% end %> 
      <%= link_to user_path(post.user), class: "normal-color no-text-decoration", title: post.user.name do %>
        <strong><%= post.user.name %></strong>
      <% end %>
      <% if post.is_belongs_to? current_user %>
          <%= link_to post_path(post), method: :delete, class: "ml-auto delete-post-icon mx-0 my-auto" do %>
            <i class="far fa-trash-alt" aria-hidden="true"></i>
          <% end %>
      <% end %>
    </div>

    <%= render "photos", {post: post} %>

    <div class="card-body" >
    <div class="row actions pb-1">
      <div id="like-icon-post-<%= post.id.to_s %>" >
        <% if post.is_liked?(current_user) %>
          <%= link_to like_path(post.liked_by_user(current_user)), method: :delete, remote: true, class:"core-sprite loved hide-text" do %><i class="fas fa-heart fa-lg" style="color:red"></i><% end %>
        <% else %>
          <%= link_to post_likes_path(post), method: :post, remote: true, class:"core-sprite love hide-text" do %><i class="far fa-heart fa-lg"></i><% end %>
        <% end %>
      </div>
      &emsp;
      <%= link_to "#", class:"core-sprite comment hide-text" do %><i class="far fa-comment fa-lg"></i><% end %>
    </div>
    <div id="like-text-post-<%= post.id.to_s %>">
      <%= render "like_text", {likes: post.likes_sort_by_created_at} if post.likes.present? %>
    </div>
    <div>
      <%= link_to user_path(post.user), class: "normal-color no-text-decoration", title: post.user.name do %>
        <strong><%= post.user.name %></strong>
      <% end %>
      <span><%= post.content %></span>
    </div>
    <div id="comment-post-<%= post.id.to_s %>">
      <%= render 'comment_list', {comments: post.comments} %>
    </div>
    <div class="light-color post-time"><%= time_ago_in_words(post.created_at).upcase %> AGO </div>
    <hr>
    <div class="row actions" id="comment-form-post-<%= post.id.to_s %>">
      <%= render 'comment_form', {post: post} %>
    </div>
  </div>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="row">
    <div class="col-8 post-card">
      <div class="card">
        <div class="card-header">
          Create Post
        </div>
        <div class="card-body">
          <%= form_for @post, :html => {:multipart => true, :class => "dropzone upload-images p-0 border-0"} do |f| %>
            <div class="form-group row mt-2">
              <div class="col-auto pr-0">
                <%= link_to user_path(current_user), class: "no-text-decoration" do %>
                  <%= image_tag avatar_url(current_user ), width: '70', height: '70', class: "round-img" %>
                <% end %>
              </div>
              <div class="col pl-0">
                <%= f.text_area :content, rows: 4, class: "form-control border-0",
                  placeholder: "Say something about this ..." %>
              </div>
            </div>
            <div class="d-none">
              <%= file_field_tag "images[]", type: :file, multiple: true, accept:'image/*', id: "img-source" %>
            </div>
            <div class="dz-message m-0"></div>
            <div class="dropzone-previews mb-3">
              <div class="upload-photos-icon">
                <i class="fa fa-plus fa-2x" aria-hidden="true" style="color:#dddfe2"></i>
              </div>
            </div>
            <div class="form-group mt-2 preview-images"></div>
            <div>
              <%= f.submit "Post", class: "btn btn-primary" %>
              <%= link_to posts_path, class: "btn btn-secondary" do %>
                <i class="fas fa-times 7x"></i>
              <% end %>
            </div>
          <% end %>
          
        </div>
      </div>
      <div id="posts">
        <%= render 'posts_list' %>
        <div class="mt-5 d-flex justify-content-center"><%= paginate @posts, theme: 'twitter-bootstrap-4'%> </div>
      </div>
    </div>

    <div class="col-4 mt-4">
      <%= render "shared/sidebar_follow" %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="row post box col-xl-12 col-lg-12 col-xs-12">
    <div class="col-lg-7 col-md-7 px-0 pt-0 d-flex post-show-img">
      <div class="align-self-center">
        <%= render "photos", {post: @post} %>
      </div>
    </div>
    <div class="col-lg-5 col-md-5 mt-sm-4 mt-md-0">
      <div class="row px-3 d-flex align-items-center">
        <%= link_to user_path(@post.user), class: "no-text-decoration" do %>
          <%= image_tag avatar_url(@post.user), class: "post-author-icon" %>
        <% end %> 
        <%= link_to user_path(@post.user), class: "normal-color no-text-decoration d-flex align-self-center",
          title: @post.user.name do %>
          <strong><%= @post.user.name %></strong>
        <% end %>
        <% if @post.is_belongs_to? current_user %>
          <%= link_to post_path(@post), method: :delete, class: "ml-auto delete-post-icon mx-0 my-auto" do %>
            <i class="far fa-trash-alt" aria-hidden="true"></i>
          <% end %>
        <% end %>
      </div>
      <hr class="mb-0">
      <div class="comment-list py-2">
      <% if @post.content.present? %>
        <div>
          <span><strong><%= @post.user.name %></strong></span>
          <span><%= @post.content %></span>
        </div>
      <% end %>
        <!-- load comment -->
        <div id="comment-post-<%= @post.id.to_s %>">
          <%= render 'comment_list', {comments: @post.comments} %>
        </div>
      </div>
        <hr class="mt-0">
        <div class="row actions pb-1">
          <div id="like-icon-post-<%= @post.id.to_s %>" >
            <% if @post.is_liked?(current_user) %>
              <%= link_to like_path(@post.liked_by_user(current_user)), method: :delete, remote: true, class:"core-sprite loved hide-text" do %><i class="fas fa-heart fa-lg" style="color:red"></i><% end %>
            <% else %>
              <%= link_to post_likes_path(@post), method: :post, remote: true, class:"core-sprite love hide-text" do %><i class="far fa-heart fa-lg"></i><% end %>
            <% end %>
          </div>
          &emsp;
          <%= link_to "#", class:"core-sprite comment hide-text" do %><i class="far fa-comment fa-lg"></i><% end %>
          <%= link_to "#", class:"core-sprite bookmark hide-text ml-auto" do %><i class="far fa-bookmark fa-lg"></i><% end %>
        </div>
        <div id="like-text-post-<%= @post.id.to_s %>">
          <%= render "like_text", {likes: @post.likes_sort_by_created_at} if @post.likes.present? %>
        </div>
        <div class="light-color post-time"><%= time_ago_in_words(@post.created_at).upcase %> AGO </div>
        <hr>
        <div class="row actions" id="comment-form-post-<%= @post.id.to_s %>">
          <%= render 'comment_form', {post: @post} %>
        </div>
      </div>
  </div>
</div>

app/views/relationships/create.js.erb
$("#follow_form").html("<%=escape_javascript(render('users/unfollow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%=escape_javascript(render('users/follow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/shared/_devisemes.html.erb
<% if resource.errors.any? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
      <div class="navbar-nav mx-auto">
        <a href="" class="nav-item nav-link" href="#">Meta</a>
        <a href="" class="nav-item nav-link" href="#">About</a>
        <a href="" class="nav-item nav-link" href="#">Blog</a>
        <a href="" class="nav-item nav-link" href="#">Jobs</a>
        <a href="" class="nav-item nav-link" href="#">Help</a>
        <a href="" class="nav-item nav-link" href="#">API</a>
        <a href="" class="nav-item nav-link" href="#">Privacy</a>
        <a href="" class="nav-item nav-link" href="#">Terms</a>
        <a href="" class="nav-item nav-link" href="#">Top Accounts</a>
        <a href="" class="nav-item nav-link" href="#">HashTags</a>
        <a href="" class="nav-item nav-link" href="#">Locations</a>
        <a href="" class="nav-item nav-link" href="#">Metagram Lite</a>
      </div>
    </div>
  </nav>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <%= link_to "MetaGram", root_path, class: "logo-metagram metagram-font-header" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <%= form_tag users_path, method: :get, class: "form-inline my-2 my-lg-0 ml-md-auto", id: "users-search" do %>
        <%= text_field_tag :search, params[:search], class: "form-control mr-sm-2 text-center common-btn",
          placeholder: "Search", autocomplete: "off" %>
      <% end %>

      <ul class="navbar-nav ml-md-auto">
        <li class="nav-item">
          <%= link_to root_path, class: "nav-link logout-icon" do %>
            <i class="fas fa-home"></i>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to user_path(current_user), class: "nav-link logout-icon" do %>
            <i class="fas fa-user-circle"></i>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete, class:"nav-link logout-icon" do %>
            <i class="fas fa-sign-out-alt"></i>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_sidebar_follow.html.erb
<div class="position-fixed">
  <div class="row">
    <div class="col-4 pr-2">
      <%= link_to user_path(current_user), class: "no-text-decoration" do %>
        <%= image_tag avatar_url(current_user ), width: '70', height: '70', class: "round-img" %>
      <% end %>
    </div>

    <div class="col-6">
      <div class="row">
        <strong>
          <%= link_to current_user.name, user_path(current_user), class: "no-text-decoration normal-color" %>
        </strong>
      </div>
      <div class="row">
        <p class="email"><%= current_user.email %></p>
      </div>
    </div>

    <div class="col-2 text-primary">
      
      <strong>
        <%= link_to "Switch", destroy_user_session_path, method: :delete, class: "no-text-decoration normal-color" %>
      </strong>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-8 text-secondary">
      <strong>Suggestions For You</strong>
    </div>
    <div class="col-4 text-right">
      <strong><%= link_to "See all", users_path, class: "no-text-decoration normal-color" %></strong>
    </div>
  </div>
  <div>
    <%= render "shared/suggest_follow" %>
  </div>
</div>
</div>

app/views/shared/_suggest_follow.html.erb
<% current_user.users_yet_follow.each do |user| %>
<% unless user.id == current_user.id %>
  <div class="row mt-4">
    <div class="col-3">
      <%= link_to user_path(user), class: "no-text-decoration" do %>
        <%= image_tag avatar_url(user), width: '50', height: '50', class: "round-img" %>
      <% end %>
    </div>

    <div class="col-6">
      <div class="row">
        <strong>
          <%= link_to user.name, user_path(user), class: "no-text-decoration normal-color" %>
        </strong>
      </div>
      <div class="row">
        <p class="email"><%= user.email %></p>
      </div>
    </div>

    <div class="col-3">
      <% if current_user.following? user %>
        <%= form_with(model:current_user.active_relationships.find_by(followed_id:user.id),html: { method: :delete }, local: true) do |f| %>
          <%= f.submit "Unfollow", class: "button-relationship-blog btn btn-secondary" %>
        <% end %>
      <% else %>
        <%= form_with(model: current_user.active_relationships.build,local: true) do |f| %>
          <div><%= hidden_field_tag :followed_id, user.id %></div>
          <%= f.submit "Follow", class: "button-relationship-blog btn btn-primary" %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>
<%end%>

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build,remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "button-relationship btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless @user.id == current_user.id %>
  <div id="follow_form">
    <% if current_user.following? @user %>
      <%= render "unfollow" %>
    <% else %>
      <%= render "follow" %>
    <% end %>
  </div>
<% end %>

app/views/users/_post.html.erb
<% posts.each do |post| %>
  <div class="col-4">
    <%= link_to post_path(post) do %>
      <div class="post-stat d-flex justify-content-center align-items-center">
        <span>
          <i class="fa fa-heart" aria-hidden="true"></i>
          <%= post.likes.size %>
          <i class="ml-3 fa fa-comment" aria-hidden="true"></i>
          <%= post.comments.size %>
        </span>
      </div>
      <%= image_tag post.photos.first.image.url(:standard), class: "card-img-top image-preview" %>
    <% end %>
  </div>
<% end %>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <span class="mr-5">
    <strong>
      <%= link_to @user.following.count, "#", class: "no-text-decoration normal-color" %>
    </strong>
    following
  </span>
  <span>
    <strong>
      <%= link_to @user.followers.count, "#", class: "no-text-decoration normal-color" %>
    </strong>
    followers
  </span>
</div>

app/views/users/_unfollow.html.erb
<%= form_with(model:current_user.active_relationships.find_by(followed_id:@user.id),html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "button-relationship btn btn-secondary" %>
<% end %>